### ISSUE TITLE
Issue on BigEndian arch (s390x)

### ISSUE THREAD

**Issue by eclipseo** [twmb/murmur3#10]
I have problem using this library on s390x.

Given the following tests using twmb/murmur3: https://github.com/eclipseo/bloom/blob/use_twmb/murmur_test.go

The tests fail on s390x arches triggering the Errorf("Backward compatibillity break."). It works on every other arches I have tested it with (all LittleEndian).

You can see the build.log here: https://koji.fedoraproject.org/koji/taskinfo?taskID=75905883

Do you have any idea what might cause this behavior? 

Thanks.

**Comment by eclipseo** [comment]
Actually this comes from the other library which assumes "Go effectively never run on big endian systems so this is fine". 
Sorry for the noise.

**Comment by twmb** [comment]
This murmur3 ensures the same hashing across architectures. The test is
comparing this repo’s murmur3 to a different implementation (in bloom.go)
that uses unsafe to convert directly to a uint64, which is not cross arch
portable (hashes are different).

So it’s somewhat of a behavior question, do you want the same hash across
arches (in which case my murmur3 is correct), or do you want more speed and
dont care about hash consistency (in which case the other code is fine)?
