### ISSUE TITLE
Seed not taken into consideration

### ISSUE THREAD

**Issue by wvh** [twmb/murmur3#3]
Hello,

The murmur32 hash resets the seed to `0` on setup, so no matter what seed is given, the hash is always calculated for seed `0`.

The `SeedNew32` constructor calls `Reset()`, which calls `reset()` through the `bmixer` interface; and this `reset()` method always sets the seed to `0` instead of the provided seed.

**Comment by twmb** [comment]
Thank you, nice find. I've fixed this and added tests for the behavior.
